### ISSUE TITLE
testrun error: AttributeError: module '__main__' has no attribute '__spec__'

### ISSUE THREAD

**Issue by rfour92** [chklovski/CheckM2#104]
Hello,

thank you for this amazing tool. I am trying to perform a testrun after installing checkM2 1.0.2 as specified in the installation guide.
I am getting this error. can you kindly tell me how to get it fixed. 

please note I am using apple silicon + rosetta, so I install tools as osx-64, not sure if it's important to disclose this information though. 

here is the full error message I get:  

> `(checkm2-env-2) ra@ checkm2 % checkm2 testrun
> /Users/ra/miniconda3/envs/checkm2-env-2/bin/checkm2:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
>   __import__('pkg_resources').run_script('CheckM2==1.0.2', 'checkm2')
> [05/26/2024 06:07:36 AM] INFO: Test run: Running quality prediction workflow on test genomes with 1 threads.
> [05/26/2024 06:07:36 AM] INFO: Running checksum on test genomes.
> [05/26/2024 06:07:36 AM] INFO: Checksum successful.
> [05/26/2024 06:07:37 AM] INFO: Calling genes in 3 bins with 1 threads:
> Traceback (most recent call last):
>   File "/Users/ra/miniconda3/envs/checkm2-env-2/bin/checkm2", line 4, in <module>
>     __import__('pkg_resources').run_script('CheckM2==1.0.2', 'checkm2')
>   File "/Users/ra/miniconda3/envs/checkm2-env-2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 680, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/Users/ra/miniconda3/envs/checkm2-env-2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1516, in run_script
>     exec(code, namespace, namespace)
>   File "/Users/ra/miniconda3/envs/checkm2-env-2/lib/python3.8/site-packages/CheckM2-1.0.2-py3.8.egg/EGG-INFO/scripts/checkm2", line 267, in <module>
>     predictor.prediction_wf(False, 'auto', False, False, False)
>   File "/Users/ra/miniconda3/envs/checkm2-env-2/lib/python3.8/site-packages/CheckM2-1.0.2-py3.8.egg/checkm2/predictQuality.py", line 103, in prediction_wf
>     GC, totalContigs, maxContigLen = self.__run_prodigal(ttable)
>   File "/Users/ra/miniconda3/envs/checkm2-env-2/lib/python3.8/site-packages/CheckM2-1.0.2-py3.8.egg/checkm2/predictQuality.py", line 386, in __run_prodigal
>     used_ttables = mp.Manager().dict()
>   File "/Users/ra/miniconda3/envs/checkm2-env-2/lib/python3.8/multiprocessing/context.py", line 57, in Manager
>     m.start()
>   File "/Users/ra/miniconda3/envs/checkm2-env-2/lib/python3.8/multiprocessing/managers.py", line 579, in start
>     self._process.start()
>   File "/Users/ra/miniconda3/envs/checkm2-env-2/lib/python3.8/multiprocessing/process.py", line 121, in start
>     self._popen = self._Popen(self)
>   File "/Users/ra/miniconda3/envs/checkm2-env-2/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
>     return Popen(process_obj)
>   File "/Users/ra/miniconda3/envs/checkm2-env-2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
>     super().__init__(process_obj)
>   File "/Users/ra/miniconda3/envs/checkm2-env-2/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
>     self._launch(process_obj)
>   File "/Users/ra/miniconda3/envs/checkm2-env-2/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
>     prep_data = spawn.get_preparation_data(process_obj._name)
>   File "/Users/ra/miniconda3/envs/checkm2-env-2/lib/python3.8/multiprocessing/spawn.py", line 183, in get_preparation_data
>     main_mod_name = getattr(main_module.__spec__, "name", None)
> AttributeError: module '__main__' has no attribute '__spec__'`

Thank you for your time :)

**Comment by prasanjoglekar** [comment]
Hi [rfour92],

Any updates on this? I have the same problem and trying to fix it

**Comment by rfour92** [comment]
> Hi [rfour92],
> 
> Any updates on this? I have the same problem and trying to fix it

Hi Prasanjoglekar, nothing from my end. I gave up on it.
