### ISSUE TITLE
Database download failed

### ISSUE THREAD

**Issue by jtamames** [chklovski/CheckM2#107]
Hello, when trying to download the database, I am finding the following error:

checkm2 database --download --path /disk2/databases/
[05/30/2024 12:54:33 PM] INFO: Command: Download database. Checking internal path information.
Traceback (most recent call last):
  File "/home/tamames/software/miniconda3/envs/checkm2/bin/checkm2", line 280, in <module>
    fileManager.DiamondDB().download_database(args.path)
  File "/home/tamames/software/miniconda3/envs/checkm2/lib/python3.8/site-packages/checkm2/fileManager.py", line 127, in download_database
    backpack_downloader.download_and_extract(download_location, DOI, progress_bar=True, no_check_version=False)
  File "/home/tamames/software/miniconda3/envs/checkm2/lib/python3.8/site-packages/checkm2/zenodo_backpack.py", line 46, in download_and_extract
    recordID = self._retrieve_record_ID(DOI)
  File "/home/tamames/software/miniconda3/envs/checkm2/lib/python3.8/site-packages/checkm2/zenodo_backpack.py", line 168, in _retrieve_record_ID
    raise ZenodoConnectionException('DOI could not be resolved. Check your DOI is correct.')
checkm2.zenodo_backpack.ZenodoConnectionException: DOI could not be resolved. Check your DOI is correct.

I tried to download the database with the link provided in #83 (https://zenodo.org/records/5571251), but that also fails. It would be great if you can provide a valid link for downloading the database.
Best,
Javier

**Comment by wwood** [comment]
Hi Javier,

I wonder if this is an issue with your internet as connection or is temporary?

-\-------------
Ben Woodcroft
Group leader, Centre for Microbiome Research, QUT
________________________________
From: Javier Tamames ***@***.***>
Sent: Thursday, May 30, 2024 9:05:24 PM
To: chklovski/CheckM2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chklovski/CheckM2] Database download failed (Issue #107)


Hello, when trying to download the database, I am finding the following error:

checkm2 database --download --path /disk2/databases/
[05/30/2024 12:54:33 PM] INFO: Command: Download database. Checking internal path information.
Traceback (most recent call last):
File "/home/tamames/software/miniconda3/envs/checkm2/bin/checkm2", line 280, in
fileManager.DiamondDB().download_database(args.path)
File "/home/tamames/software/miniconda3/envs/checkm2/lib/python3.8/site-packages/checkm2/fileManager.py", line 127, in download_database
backpack_downloader.download_and_extract(download_location, DOI, progress_bar=True, no_check_version=False)
File "/home/tamames/software/miniconda3/envs/checkm2/lib/python3.8/site-packages/checkm2/zenodo_backpack.py", line 46, in download_and_extract
recordID = self._retrieve_record_ID(DOI)
File "/home/tamames/software/miniconda3/envs/checkm2/lib/python3.8/site-packages/checkm2/zenodo_backpack.py", line 168, in _retrieve_record_ID
raise ZenodoConnectionException('DOI could not be resolved. Check your DOI is correct.')
checkm2.zenodo_backpack.ZenodoConnectionException: DOI could not be resolved. Check your DOI is correct.

I tried to download the database with the link provided in #83<https://github.com/chklovski/CheckM2/issues/83> (https://zenodo.org/records/5571251), but that also fails. It would be great if you can provide a valid link for downloading the database.
Best,
Javier

―

**Comment by jtamames** [comment]
Hello Ben

Thanks for responding. Apparently my connectivity is ok, and I am able to download other files and databases from external sources

Best,
J

**Comment by wwood** [comment]
Hmm. It's just a bit strange as I'm not having any issue downloading, at least the file from zenodo - haven't checked with checkm2 data.

**Comment by martinmchugh** [comment]
Was this resolved? I am getting the same error with checkm2 v1.1.0 installed with mamba. No issues with connectivity

**Comment by dgroves6** [comment]
Hi,

I agree with https://github.com/chklovski/CheckM2/issues/72 that the easiest workaround is to directly download the database from the URL with `wget`, etc

Here's some insight on the error and a proposed solution though. I believe the underlying issue is actually on the developer-side in `zenodo_backpack.py`

### Error Messages and Debugging
This error "DOI could not be resolved. Check your DOI is correct." isn't accurate. The DOI is of the checkm database is correct, but adding debugging messages to `zenodo_backpack.py` reveals an Error 429 (Too Many Requests) which results whenever an unknown/low-trust client (possibily on a noisy subnet) accesses the (Zenodo) server too frequently. 

There are three function inside `zenodo_backpack.py` that send requests to the Zenodo server, and by adding debugging messages we see they all result from Error 429, but due to incorrectly-handled exceptions they seemingly appear as different errors:
1. `Result of _retrieve_record_ID: <Response [429]>`
    - console error: "checkm2.zenodo_backpack.ZenodoConnectionException: DOI could not be resolved. Check your DOI is correct."
2. `Result of _retrieve_record_metadata: <Response [429]>`
    - consoler error: "TypeError: cannot unpack non-iterable NoneType object"
3. `Result of _download_file: <Response [429]>`
    - console error: "tarfile.ReadError: file could not be opened successfully"

This is one of those full HTTP responses:
```
 <html>
    <head><title>429 Too Many Requests</title></head>
        <body>
            <center><h1>429 Too Many Requests</h1></center>
            <hr><center>nginx</center>
        </body>
</html>
```

And in fact when the third step `_download_file` fails funny enough these are the contents of: `checkm2_database.tar.gz`
```
cat ~/databases/checkm2_database.tar.gz
<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

### Common Causes/Fixes

One common fix is to take the value of "Retry-After" (or make a guess) and wait that long before making another request or to use an exponential backoff strategy if you actually are making a ton of requests to the server. But 1) we get an Error 429 on the very first request, 2) there is no "Retry-After" tag in the above HTML response (the Zenodo server might not be configured to send that info back) and 3) we're only making three requests so an exponential backoff strategy is overkill.

The first thing one should actually look for is if the request is sending a header to the server. The script isn't using headers: https://github.com/chklovski/CheckM2/blob/f0a9eb291df899890e23542591db5c852e200c35/checkm2/zenodo_backpack.py#L164

So the Zenodo server is classifying the request as anonymous (servers may flag default/trivial headers to minimize risk). The easiest developer fix would be to include a meaningful header related to CheckM2, or a more robust fix would be to fully utilize Zenodo's REST API (https://developers.zenodo.org/)

### Tested Solution
Creating a header like this and passing it as an arg completely fixed the problem for me!
```
HEADERS= {
    "User-Agent": "checkm2/1.1.0 (contact: <developer.email@example.com>)"
}
...
r = requests.get(DOI, headers=HEADERS, timeout=15)
```

### Summary
- The try/except blocks could have used more robust conditional checks (maybe for specific HTTP status codes 200, 404, 429, 500), possibly standardize debugging messages between the three internal class functions to eliminate the variable console errors, and maybe print the actual status code in the except block instead of raising an assumed error.
- That being said, cross-talk between client and server is not trivial. Servers are configured differently, so if you're already on a trusted network it's really hard to replicate this type of bug. I'm personally using AWS EC2, and cloud networks are known to have these issues which is the only reason I came across this.
- I love CheckM2 and the cool algorithmic changes it implemented. Like I said in the beginning, the easy fix is to just download from the URL directly, but as a Biochemist ➡️ Bioinformatics Scientist ➡️ Software Engineer that has run into similar bugs recently I wanted to write a detailed post for people of all experience levels. 
- Might open a PR for 1.1.1, might not 🤷‍♂️
- If you read this far, power to you - thanks for the read 🫡

Cheers,
Dan
