### ISSUE TITLE
TypeError: split() error

### ISSUE THREAD

**Issue by marshjw** [chklovski/CheckM2#110]
Hi,

I'm running CheckM2 with the following command:

checkm2 \
    predict \
        --threads 20 \
        --input $(cat {input_file}) \
        --output-directory {output_dir} \
        --allmodels \
        --extension fasta \
        --database_path {database_path}
       
However, I'm getting the error:

```
[07/29/2024 09:58:00 AM] INFO: Processing DIAMOND output
Traceback (most recent call last):
  File "/code/conda_envs/checkm2/bin/checkm2", line 4, in <module>
    __import__('pkg_resources').run_script('CheckM2==1.0.2', 'checkm2')
  File "/code/conda_envs/checkm2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 752, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/code/conda_envs/checkm2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1718, in run_script
    exec(code, namespace, namespace)
  File "/code/conda_envs/checkm2/lib/python3.8/site-packages/CheckM2-1.0.2-py3.8.egg/EGG-INFO/scripts/checkm2", line 244, in <module>
    predictor.prediction_wf(args.genes, mode, args.dbg_cos, args.dbg_vectors,
  File "/code/conda_envs/checkm2/lib/python3.8/site-packages/CheckM2-1.0.2-py3.8.egg/checkm2/predictQuality.py", line 149, in prediction_wf
    results[['GenomeName', 'ProteinID']] = results['header'].str.split(diamond_search.separator, 1, expand=True)
  File "/.local/lib/python3.8/site-packages/pandas/core/strings/accessor.py", line 129, in wrapper
    return func(self, *args, **kwargs)
TypeError: split() takes from 1 to 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given
```

I installed CheckM2 using pip. Here's my environment:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_tflow_select             2.3.0                     eigen
abseil-cpp                20200923.3           h9c3ff4c_0    conda-forge
absl-py                   2.1.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.9.5            py38h01eb140_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.3              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
blinker                   1.8.2              pyhd8ed1ab_0    conda-forge
boost-cpp                 1.70.0               h7b93d67_3    conda-forge
brotli-python             1.1.0            py38h17151c0_1    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.32.3               h4bc722e_0    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
cachetools                4.2.4              pyhd8ed1ab_0    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0           py38h6d47a40_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
checkm2                   1.0.2                    pypi_0    pypi
click                     8.1.7           unix_pyh707e725_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
cryptography              42.0.8           py38h1407eca_0    conda-forge
diamond                   2.0.4                h56fc30b_0    bioconda
frozenlist                1.4.1            py38h01eb140_0    conda-forge
gast                      0.3.3                      py_0    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
google-auth               1.35.0             pyh6c4a22f_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grpc-cpp                  1.39.0               hae934f6_5
grpcio                    1.46.3           py38h2e9ca35_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
h5py                      2.10.0          nompi_py38h9915d05_106    conda-forge
hdf5                      1.10.6               h3ffc7dd_1
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
importlib-metadata        8.2.0              pyha770c72_0    conda-forge
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
libblas                   3.9.0           20_linux64_openblas    conda-forge
libcblas                  3.9.0           20_linux64_openblas    conda-forge
libcurl                   7.88.1               hdc1c0ab_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgfortran-ng            14.1.0               h69a702a_0    conda-forge
libgfortran5              14.1.0               hc5f4f2c_0    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
liblapack                 3.9.0           20_linux64_openblas    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libprotobuf               3.17.2               h780b84a_1    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              14.1.0               hc0a3c3a_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
lightgbm                  3.2.1            py38h709712a_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markdown                  3.6                pyhd8ed1ab_0    conda-forge
markupsafe                2.1.5            py38h01eb140_0    conda-forge
multidict                 6.0.5            py38h01eb140_0    conda-forge
ncurses                   6.5                  h59595ed_0    conda-forge
numpy                     1.20.3           py38h8246c76_2    conda-forge
oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
openssl                   3.3.1                h4bc722e_2    conda-forge
opt_einsum                3.3.0              pyhc1e730c_2    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pandas                    1.4.0            py38h43a58ef_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
prodigal                  2.6.3                h031d066_9    bioconda
protobuf                  3.17.2           py38h709712a_0    conda-forge
pyasn1                    0.6.0              pyhd8ed1ab_0    conda-forge
pyasn1-modules            0.4.0              pyhd8ed1ab_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_1    conda-forge
pyopenssl                 24.2.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.8.19          hd12c33a_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-flatbuffers        1.12               pyhd8ed1ab_1    conda-forge
python_abi                3.8                      4_cp38    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
re2                       2021.04.01           h9c3ff4c_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
requests-oauthlib         2.0.0              pyhd8ed1ab_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
scikit-learn              0.23.2           py38h5d63f67_3    conda-forge
scipy                     1.8.0            py38h56a6a73_1    conda-forge
setuptools                71.0.4             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               hdb0a2a9_1    conda-forge
tensorboard               2.4.1              pyhd8ed1ab_1    conda-forge
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
tensorflow                2.3.0           eigen_py38h71ff20e_0
tensorflow-base           2.3.0           eigen_py38hb57a387_0
tensorflow-estimator      2.4.0              pyh9656e83_0    conda-forge
termcolor                 2.4.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.5.0              pyhc1e730c_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tqdm                      4.66.4             pyhd8ed1ab_0    conda-forge
typing-extensions         4.12.2               hd8ed1ab_0    conda-forge
typing_extensions         4.12.2             pyha770c72_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
werkzeug                  3.0.3              pyhd8ed1ab_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
wrapt                     1.16.0           py38h01eb140_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yarl                      1.9.4            py38h01eb140_0    conda-forge
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstandard                 0.19.0           py38h0a891b7_0    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge
```

Thanks for your help.

**Comment by harrytchild** [comment]
Hi, 

I am having the similar issue running the checkm2 testrun. I followed the "Run without installing" instructions. I get the following error:
$ bin/checkm2 testrun --database_path CheckM2_database/uniref100.KO.1.dmnd
[09/05/2024 09:14:18 AM] INFO: Calling genes in 3 bins with 30 threads:
    Finished processing 3 of 3 (100.00%) bins.
[09/05/2024 09:14:33 AM] INFO: Calculating metadata for 3 bins with 30 threads:
    Finished processing 3 of 3 (100.00%) bin metadata.
[09/05/2024 09:14:34 AM] INFO: Annotating input genomes with DIAMOND using 30 threads
[09/05/2024 09:15:00 AM] INFO: Processing DIAMOND output
Traceback (most recent call last):
  File "bin/checkm2", line 267, in <module>
    predictor.prediction_wf(False, 'auto', False, False, False)
  File "/localdata/harry/programs/checkm2/bin/../checkm2/predictQuality.py", line 149, in prediction_wf
    results[['GenomeName', 'ProteinID']] = results['header'].str.split(diamond_search.separator, 1, expand=True)
  File "/home/harry/.local/lib/python3.8/site-packages/pandas/core/strings/accessor.py", line 129, in wrapper
    return func(self, *args, **kwargs)
TypeError: split() takes from 1 to 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given

Any help to resolve this would be great!

**Comment by marshomics** [comment]
I got it to work by changing these lines in `predictQuality.py` from:

```
results[['GenomeName', 'ProteinID']] = results['header'].str.split(diamond_search.separator, 1, expand=True)
results[['Ref100_hit', 'Kegg_annotation']] = results['annotation'].str.split('~', 1, expand=True)

```
to:

```
results[['GenomeName', 'ProteinID']] = results['header'].str.split(diamond_search.separator, n=1, expand=True)
results[['Ref100_hit', 'Kegg_annotation']] = results['annotation'].str.split('~', n=1, expand=True)
```

and then running it locally: `bin/checkm2`

**Comment by harrytchild** [comment]
Hi,

Thanks for looking into this. After making this change I get the following error message:
```
[09/06/2024 10:04:29 AM] INFO: Annotating input genomes with DIAMOND using 1 threads
[09/06/2024 10:14:03 AM] INFO: Processing DIAMOND output
[09/06/2024 10:14:03 AM] INFO: Predicting completeness and contamination using ML models.
Traceback (most recent call last):
  File "bin/checkm2", line 267, in <module>
    predictor.prediction_wf(False, 'auto', False, False, False)
  File "/localdata/harry/programs/checkm2/bin/../checkm2/predictQuality.py", line 205, in prediction_wf
    vector_array = feature_vectors.iloc[:, 1:].values.astype(np.float)
  File "/home/harry/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
I tried editing the script to include just "float" and "np.float64", but both of these then lead to this error:
```
[09/06/2024 10:34:36 AM] INFO: Annotating input genomes with DIAMOND using 1 threads
[09/06/2024 10:45:50 AM] INFO: Processing DIAMOND output
[09/06/2024 10:45:50 AM] INFO: Predicting completeness and contamination using ML models.
Traceback (most recent call last):
  File "bin/checkm2", line 267, in <module>
    predictor.prediction_wf(False, 'auto', False, False, False)
  File "/localdata/harry/programs/checkm2/bin/../checkm2/predictQuality.py", line 215, in prediction_wf
    specific_result_comp, scaled_features = modelProc.run_prediction_specific(vector_array, specific_model_vector_len)
  File "/localdata/harry/programs/checkm2/bin/../checkm2/modelProcessing.py", line 68, in run_prediction_specific
    scaled_vector = self.minmax_scaler.transform(vector_array)
  File "/home/harry/.local/lib/python3.8/site-packages/sklearn/utils/_set_output.py", line 157, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/harry/.local/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 525, in transform
    if self.clip:
AttributeError: 'MinMaxScaler' object has no attribute 'clip'
```
I fear I'm going down a but of a rabbit hole if I continue trying to fix myself, but maybe you can find a better solution which can be implemented?

Cheers!

**Comment by harrytchild** [comment]
Thanks for your help. I agree it is a dependancy nightmare, but I don't envy the developers for the maintenance they have to do! 

Unfortunately, I'm still getting errors with your installation method. Are you able to attach a YML file of your conda environment so I can try installing that with all the specific package versions you have?

Cheers

**Comment by marshomics** [comment]
Sorry to hear that. Sure, here it is:

```
name: checkm2
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - abseil-cpp=20210324.2=h9c3ff4c_0
  - aiohappyeyeballs=2.4.0=pyhd8ed1ab_0
  - aiohttp=3.10.5=py38h2019614_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - astor=0.8.1=pyh9f0ad1d_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - blast=2.16.0=hc155240_2
  - blinker=1.8.2=pyhd8ed1ab_0
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.33.1=heb4867d_0
  - ca-certificates=2024.8.30=hbcca054_0
  - cachetools=4.2.4=pyhd8ed1ab_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.0=py38heb5c249_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=39.0.0=py38h1724139_0
  - curl=7.87.0=h6312ad2_0
  - diamond=2.1.8=h43eeafb_0
  - entrez-direct=22.4=he881be0_0
  - frozenlist=1.4.1=py38h01eb140_0
  - gast=0.3.3=py_0
  - gettext=0.22.5=he02047a_3
  - gettext-tools=0.22.5=he02047a_3
  - giflib=5.2.2=hd590300_0
  - google-auth=1.35.0=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyhd8ed1ab_1
  - grpc-cpp=1.37.1=hfc4d69e_3
  - grpcio=1.37.1=py38hdd6454d_0
  - h2=4.1.0=pyhd8ed1ab_0
  - h5py=2.10.0=nompi_py38h9915d05_106
  - hdf5=1.10.6=nompi_h6a2412b_1114
  - hpack=4.0.0=pyh9f0ad1d_0
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=68.2=h9c3ff4c_0
  - idna=3.8=pyhd8ed1ab_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - jpeg=9e=h0b41bf4_3
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.20.1=hf9c8cef_0
  - ld_impl_linux-64=2.40=hf3520f5_7
  - libasprintf=0.22.5=he8f35ee_3
  - libasprintf-devel=0.22.5=he8f35ee_3
  - libblas=3.9.0=20_linux64_openblas
  - libcblas=3.9.0=20_linux64_openblas
  - libcurl=7.87.0=h6312ad2_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgettextpo=0.22.5=he02047a_3
  - libgettextpo-devel=0.22.5=he02047a_3
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgomp=14.1.0=h77fa898_1
  - libidn2=2.3.7=hd590300_0
  - liblapack=3.9.0=20_linux64_openblas
  - libnghttp2=1.51.0=hdcd2b5c_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.25=pthreads_h413a1c8_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=3.15.8=h780b84a_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - lightgbm=3.2.1=py38h709712a_0
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py38h01eb140_0
  - multidict=6.0.5=py38h01eb140_0
  - ncbi-vdb=3.1.1=h4ac6f70_1
  - ncurses=6.5=he02047a_1
  - numpy=1.20.3=py38h8246c76_2
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openssl=1.1.1w=hd590300_0
  - opt_einsum=3.3.0=pyhc1e730c_2
  - packaging=24.1=pyhd8ed1ab_0
  - perl=5.32.1=7_hd590300_perl5
  - perl-archive-tar=2.40=pl5321hdfd78af_0
  - perl-carp=1.50=pl5321hd8ed1ab_0
  - perl-common-sense=3.75=pl5321hd8ed1ab_0
  - perl-compress-raw-bzip2=2.201=pl5321h166bdaf_0
  - perl-compress-raw-zlib=2.202=pl5321h166bdaf_0
  - perl-encode=3.21=pl5321hd590300_0
  - perl-exporter=5.74=pl5321hd8ed1ab_0
  - perl-exporter-tiny=1.002002=pl5321hd8ed1ab_0
  - perl-extutils-makemaker=7.70=pl5321hd8ed1ab_0
  - perl-io-compress=2.201=pl5321hdbdd923_2
  - perl-io-zlib=1.14=pl5321hdfd78af_0
  - perl-json=4.10=pl5321hdfd78af_1
  - perl-json-xs=4.03=pl5321h4ac6f70_3
  - perl-list-moreutils=0.430=pl5321hdfd78af_0
  - perl-list-moreutils-xs=0.430=pl5321h031d066_2
  - perl-parent=0.241=pl5321hd8ed1ab_0
  - perl-pathtools=3.75=pl5321h166bdaf_0
  - perl-scalar-list-utils=1.63=pl5321h166bdaf_0
  - perl-storable=3.15=pl5321h166bdaf_0
  - perl-types-serialiser=1.01=pl5321hdfd78af_0
  - pip=24.2=pyh8b19718_1
  - prodigal=2.6.3=h031d066_9
  - protobuf=3.15.8=py38h709712a_0
  - pyasn1=0.6.0=pyhd8ed1ab_0
  - pyasn1-modules=0.4.0=pyhd8ed1ab_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pyjwt=2.9.0=pyhd8ed1ab_1
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.15=h257c98d_0_cpython
  - python-flatbuffers=1.12=pyhd8ed1ab_1
  - python_abi=3.8=5_cp38
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - re2=2021.08.01=h9c3ff4c_0
  - readline=8.2=h8228510_1
  - requests=2.32.3=pyhd8ed1ab_0
  - requests-oauthlib=2.0.0=pyhd8ed1ab_0
  - rpsbproc=0.5.0=h6a68c12_0
  - rsa=4.9=pyhd8ed1ab_0
  - scikit-learn=0.23.2=py38h5d63f67_3
  - scipy=1.8.0=py38h56a6a73_1
  - setuptools=73.0.1=pyhd8ed1ab_0
  - six=1.15.0=pyh9f0ad1d_0
  - snappy=1.1.10=hdb0a2a9_1
  - sqlite=3.46.0=h6d4b2fc_0
  - tensorboard=2.4.1=pyhd8ed1ab_1
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.4.3=py38h578d9bd_0
  - tensorflow-base=2.4.3=py38h83f5f1d_0
  - tensorflow-estimator=2.4.0=pyh9656e83_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - tqdm=4.66.5=pyhd8ed1ab_0
  - typing-extensions=3.7.4.3=0
  - typing_extensions=3.7.4.3=py_0
  - urllib3=2.2.2=pyhd8ed1ab_1
  - werkzeug=3.0.4=pyhd8ed1ab_0
  - wget=1.20.3=ha56f1ee_1
  - wheel=0.44.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yarl=1.9.4=py38h01eb140_0
  - zipp=3.20.1=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py38h62bed22_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - absl-py==0.15.0
      - termcolor==1.1.0
      - wrapt==1.12.1
prefix: /conda_envs/checkm2
```
