### ISSUE TITLE
AF_UNIX path too long

### ISSUE THREAD

**Issue by susheelbhanu** [chklovski/CheckM2#111]
Hi, 

Have any of you come across this issue before? 

```bash
Tue 30 Jul 14:35:28 BST 2024
[07/30/2024 02:35:33 PM] INFO: Running CheckM2 version 1.0.1
[07/30/2024 02:35:33 PM] INFO: Custom database path provided for predict run. Checking database at /ei/.project-scratch/0/0e51ef86-0156-4e79-ad12-c5411c0a5496/databases/CheckM2_database/uniref100.KO.1.dmnd...
[07/30/2024 02:35:35 PM] INFO: Running quality prediction workflow with 64 threads.
[07/30/2024 02:35:36 PM] INFO: Calling genes in 3 bins with 64 threads:
Process SyncManager-1:
Traceback (most recent call last):
  File "/hpc-home/kar23heg/miniconda3/envs/checkm2/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/hpc-home/kar23heg/miniconda3/envs/checkm2/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/hpc-home/kar23heg/miniconda3/envs/checkm2/lib/python3.7/multiprocessing/managers.py", line 589, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/hpc-home/kar23heg/miniconda3/envs/checkm2/lib/python3.7/multiprocessing/managers.py", line 145, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/hpc-home/kar23heg/miniconda3/envs/checkm2/lib/python3.7/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/hpc-home/kar23heg/miniconda3/envs/checkm2/lib/python3.7/multiprocessing/connection.py", line 581, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
Traceback (most recent call last):
  File "/hpc-home/kar23heg/miniconda3/envs/checkm2/bin/checkm2", line 211, in <module>
    args.resume, args.remove_intermediates, args.ttable)
  File "/hpc-home/kar23heg/miniconda3/envs/checkm2/lib/python3.7/site-packages/checkm2/predictQuality.py", line 103, in prediction_wf
    GC = self.__run_prodigal(ttable)
  File "/hpc-home/kar23heg/miniconda3/envs/checkm2/lib/python3.7/site-packages/checkm2/predictQuality.py", line 380, in __run_prodigal
    used_ttables = mp.Manager().dict()
  File "/hpc-home/kar23heg/miniconda3/envs/checkm2/lib/python3.7/multiprocessing/context.py", line 56, in Manager
    m.start()
  File "/hpc-home/kar23heg/miniconda3/envs/checkm2/lib/python3.7/multiprocessing/managers.py", line 567, in start
    self._address = reader.recv()
  File "/hpc-home/kar23heg/miniconda3/envs/checkm2/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/hpc-home/kar23heg/miniconda3/envs/checkm2/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/hpc-home/kar23heg/miniconda3/envs/checkm2/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

Which path is this referring to?

Thank you,
Susheel

**Comment by wwood** [comment]
I think this. Might be due to a non standard tempdir being set. I've seen problems in other software very similar specifically on python 3.12, not sure if that is what you are using.

**Comment by susheelbhanu** [comment]
Thanks @wwood, that makes sense. I moved to a tmpdir with a shorter path and that seems to fix it. 

Cheers, 
Susheel
