### ISSUE TITLE
Bug on a fresh install

### ISSUE THREAD

**Issue by asaldivar93** [chklovski/CheckM2#115]
When running checkm2 on a new environment I got this error:

`Traceback (most recent call last):
  File "/opt/asaldivar/miniconda3/envs/checkm2/bin/checkm2", line 27, in <module>
    from checkm2 import predictQuality
  File "/opt/asaldivar/miniconda3/envs/checkm2/lib/python3.6/site-packages/checkm2/predictQuality.py", line 1, in <module>
    from checkm2 import modelProcessing
  File "/opt/asaldivar/miniconda3/envs/checkm2/lib/python3.6/site-packages/checkm2/modelProcessing.py", line 17, in <module>
    from tensorflow import keras
  File "/opt/asaldivar/miniconda3/envs/checkm2/lib/python3.6/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/opt/asaldivar/miniconda3/envs/checkm2/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/opt/asaldivar/miniconda3/envs/checkm2/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 28, in <module>
    from absl import logging
  File "/opt/asaldivar/miniconda3/envs/checkm2/lib/python3.6/site-packages/absl/logging/__init__.py", line 97, in <module>
    from absl import flags
  File "/opt/asaldivar/miniconda3/envs/checkm2/lib/python3.6/site-packages/absl/flags/__init__.py", line 35, in <module>
    from absl.flags import _argument_parser
  File "/opt/asaldivar/miniconda3/envs/checkm2/lib/python3.6/site-packages/absl/flags/_argument_parser.py", line 82, in <module>
    class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
`

Traced it back to a Tensorflow issue: [#64926](https://github.com/tensorflow/tensorflow/issues/64926#issue-2220994621)

The hotfix was:

`pip install absl-py==1.1.0`

**Comment by vdejager** [comment]
Thanks, this was also the issue on our installation.

**Comment by lijierr** [comment]
Same here, installed via conda. Any ideas?
