### ISSUE TITLE
No space left of device

### ISSUE THREAD

**Issue by susheelbhanu** [chklovski/CheckM2#19]
Hi, 

I'm running `checkm2` on 3000 bins and running into the following error:
```
[09/01/2022 01:51:32 AM] INFO: Calculating metadata for 3000 bins with 4 threads:
[09/01/2022 01:52:28 AM] INFO: Annotating input genomes with DIAMOND using 4 threads
No space left on device
No space left on device
terminate called after throwing an instance of 'File_write_exception'
  what():  Error writing file /tmp/tmpf39hhc0_/diamond-tmp-AvchIO
No space left on device
terminate called after throwing an instance of 'File_write_exception'
  what():  Error writing file /tmp/tmp8fczbzb7/diamond-tmp-GPaMRF
No space left on device
terminate called after throwing an instance of 'File_write_exception'
  what():  Error writing file /tmp/tmpn4zhr9gd/diamond-tmp-FwJlQ5
No space left on device
terminate called after throwing an instance of 'File_write_exception'
  what():  Error writing file /tmp/tmpi3bsvtgx/diamond-tmp-jIZPmg
Traceback (most recent call last):
  File "/mnt/lscratch/users/sbusi/SnakemakeBinning/workflow/rules/../../submodules/bin/checkm2", line 154, in <module>
    predictor.prediction_wf(args.genes, mode, args.dbg_cos, args.dbg_vectors, args.stdout)
  File "/mnt/lscratch/users/sbusi/SnakemakeBinning/submodules/bin/../checkm2/predictQuality.py", line 103, in prediction_wf
    diamond_out = diamond_search.run(prodigal_files)
  File "/mnt/lscratch/users/sbusi/SnakemakeBinning/submodules/bin/../checkm2/diamond.py", line 126, in run
    self.__call_diamond(self.__concatenate_proteins(chunk), diamond_out)
  File "/mnt/lscratch/users/sbusi/SnakemakeBinning/submodules/bin/../checkm2/diamond.py", line 73, in __call_diamond
    sequenceClasses.SeqReader().write_fasta(seq_object, temp_diamond_input.name)
  File "/mnt/lscratch/users/sbusi/SnakemakeBinning/submodules/bin/../checkm2/sequenceClasses.py", line 104, in write_fasta
    fout.write('>' + seqId + '\n')
OSError: [Errno 28] No space left on device
```

Looks similar to the following issue: https://github.com/bbuchfink/diamond/issues/267

However, the SLURM efficiency suggests that I have more than sufficient resources
```
Job ID: 2889109
Cluster: iris
User/Group: sbusi/clusterusers
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 4
CPU Utilized: 22:40:03
CPU Efficiency: 96.88% of 23:23:48 core-walltime
Job Wall-clock time: 05:50:57
Memory Utilized: 11.43 GB
Memory Efficiency: 10.84% of 105.47 GB
```

Does one have to use the `low mem` setting for this?

Thank you,
Susheel 

EDIT: I've verified and I have plenty of disk space and also inode space :)

**Comment by wwood** [comment]
Hi Susheel - this looks like a disk out of space, not CPU or RAM, right?

**Comment by susheelbhanu** [comment]
Hey Ben, 

I checked and it looks okay
```
Directory                              Used  Soft quota  Hard quota  Grace period
/mnt/lscratch/                    6.658T         10T         11T          none   (size)
/mnt/lscratch/                     1459512     4000000     4100000          none (files)
```

**Comment by wwood** [comment]
But the directory being written is not in that directory, right, but is in /tmp?

**Comment by susheelbhanu** [comment]
🤦🏽‍♂️ Makes sense.. Sorry!

Guess I'll have to export to a different `/tmp` then?
