### ISSUE TITLE
lib_lightgbm.so: failed to map segment from shared object

### ISSUE THREAD

**Issue by jolespin** [chklovski/CheckM2#23]
Here was my installation command: 

```
mamba env create -n checkm2_env -f checkm2/checkm2.yml && pip install --no-deps checkm2/
```

Here is the error:
```
(checkm2_env) [jespinoz@login02 Test]$ checkm2 -h
Traceback (most recent call last):
  File "/expanse/projects/jcl110/anaconda3/envs/checkm2_env/bin/checkm2", line 27, in <module>
    from checkm2 import predictQuality
  File "/expanse/projects/jcl110/anaconda3/envs/checkm2_env/lib/python3.9/site-packages/checkm2/predictQuality.py", line 7, in <module>
    from checkm2 import modelProcessing
  File "/expanse/projects/jcl110/anaconda3/envs/checkm2_env/lib/python3.9/site-packages/checkm2/modelProcessing.py", line 11, in <module>
    import lightgbm as lgb
  File "/expanse/projects/jcl110/anaconda3/envs/checkm2_env/lib/python3.9/site-packages/lightgbm/__init__.py", line 8, in <module>
    from .basic import Booster, Dataset, Sequence, register_logger
  File "/expanse/projects/jcl110/anaconda3/envs/checkm2_env/lib/python3.9/site-packages/lightgbm/basic.py", line 110, in <module>
    _LIB = _load_lib()
  File "/expanse/projects/jcl110/anaconda3/envs/checkm2_env/lib/python3.9/site-packages/lightgbm/basic.py", line 101, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/expanse/projects/jcl110/anaconda3/envs/checkm2_env/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/expanse/projects/jcl110/anaconda3/envs/checkm2_env/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /expanse/projects/jcl110/anaconda3/envs/checkm2_env/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so: failed to map segment from shared object
```

I reinstalled `lightgbm` and got the same error.

**Comment by jolespin** [comment]
Not happening with v1.0.1
