### ISSUE TITLE
--allmodels is broken.

### ISSUE THREAD

**Issue by GabeAl** [chklovski/CheckM2#33]
```
$ time checkm2 predict -i ~/Downloads/holden/ -o ~/Downloads/holden/temp --force --allmodels --remove_intermediates -t 16 -x fa
[12/29/2022 08:01:37 PM] INFO: Running quality prediction workflow with 16 threads.
[12/29/2022 08:01:38 PM] INFO: Calling genes in 3 bins with 16 threads:
    Finished processing 3 of 3 (100.00%) bins.
[12/29/2022 08:01:47 PM] INFO: Calculating metadata for 3 bins with 16 threads:
    Finished processing 3 of 3 (100.00%) bin metadata.
[12/29/2022 08:01:48 PM] INFO: Annotating input genomes with DIAMOND using 16 threads
[12/29/2022 08:02:47 PM] INFO: Processing DIAMOND output
[12/29/2022 08:02:48 PM] INFO: Predicting completeness and contamination using ML models.
[12/29/2022 08:02:53 PM] INFO: Parsing all results and constructing final output table.
Traceback (most recent call last):
  File "/home/user/.conda/envs/checkm2/bin/checkm2", line 4, in <module>
    __import__('pkg_resources').run_script('CheckM2==1.0.0', 'checkm2')
  File "/home/user/.conda/envs/checkm2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/user/.conda/envs/checkm2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1472, in run_script
    exec(code, namespace, namespace)
  File "/home/user/.conda/envs/checkm2/lib/python3.8/site-packages/CheckM2-1.0.0-py3.8.egg/EGG-INFO/scripts/checkm2", line 182, in <module>
    predictor.prediction_wf(args.genes, mode, args.dbg_cos, args.dbg_vectors, args.stdout,
  File "/home/user/.conda/envs/checkm2/lib/python3.8/site-packages/CheckM2-1.0.0-py3.8.egg/checkm2/predictQuality.py", line 250, in prediction_wf
    final_results['Contamination'] = np.round(general_results_cont, 2)
NameError: name 'general_results_cont' is not defined
```
Works without --allmodels

**Comment by chklovski** [comment]
Thanks, fixed in latest commit. Let me know if there's any further issues with this.
