### ISSUE TITLE
Checkm 2 fails when a genome has lowercase bases

### ISSUE THREAD

**Issue by fplaza** [chklovski/CheckM2#37]
Hi!

Checkm2 expects uppercase bases and crashes when it is not the case.
https://github.com/chklovski/CheckM2/blob/badae4e495fc415e3acc8eacc66989f5c574787d/checkm2/prodigal.py#L72

```
Traceback (most recent call last):
  File "miniconda3/envs/checkm2_env/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "miniconda3/envs/checkm2_env/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "miniconda3/envs/checkm2_env/lib/python3.9/site-packages/CheckM2-1.0.0-py3.9.egg/checkm2/predictQuality.py", line 322, in __set_up_prodigal_thread
    v_N50, v_avg_gene_len, v_total_bases, v_cds_count, v_GC = prodigal_thread.run(bin, ttable)
  File "miniconda3/envs/checkm2_env/lib/python3.9/site-packages/CheckM2-1.0.0-py3.9.egg/checkm2/prodigal.py", line 77, in run
    GC = float(GC/(AT + GC))
ZeroDivisionError: division by zero
```

**Comment by chklovski** [comment]
Fixed in latest commit, thanks for spotting that.

**Comment by Caiyulu-818** [comment]
[04/06/2023 04:18:18 AM] INFO: Running quality prediction workflow with 21 threads.
[04/06/2023 04:55:23 AM] INFO: Re-using protein files from output directory: /media/tree/checkm2/mag2/protein_files
Traceback (most recent call last):
  File "/application/checkm2/bin/checkm2", line 211, in <module>
    args.resume, args.remove_intermediates, args.ttable)
  File "/application/checkm2/bin/../checkm2/predictQuality.py", line 116, in prediction_wf
    metadata_df = self.__calculate_metadata(prodigal_files)
  File "/application/checkm2/bin/../checkm2/predictQuality.py", line 419, in __calculate_metadata
    self.threads_per_bin = max(1, int(self.total_threads / len(faa_files)))
ZeroDivisionError: division by zero
also the error but because of different reason!
