### ISSUE TITLE
PermissionError: diamond_path.json

### ISSUE THREAD

**Issue by nick-youngblut** [chklovski/CheckM2#39]
```
checkm2 database --download --path .
[01/11/2023 09:37:17 PM] INFO: Command: Download database. Checking internal path information.
[01/11/2023 09:37:21 PM] INFO: Downloading https://zenodo.org/api/files/fd3bc532-cd84-4907-b078-2e05a1e46803/checkm2_database.tar.gz to ./checkm2_database.tar.gz.
100%|██████████████████████████████████████████████████████████████████████████████████████████| 1.74G/1.74G [12:53<00:00, 2.24MiB/s]
[01/11/2023 09:50:52 PM] INFO: Extracting files from archive...
[01/11/2023 09:55:08 PM] INFO: Verifying version and checksums...
[01/11/2023 09:55:08 PM] INFO: Verification success.
Traceback (most recent call last):
  File "/opt/conda/bin/checkm2", line 4, in <module>
    __import__('pkg_resources').run_script('CheckM2==1.0.0', 'checkm2')
  File "/opt/conda/lib/python3.9/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/conda/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/opt/conda/lib/python3.9/site-packages/CheckM2-1.0.0-py3.9.egg/EGG-INFO/scripts/checkm2", line 244, in <module>
    fileManager.DiamondDB().download_database(args.path)
  File "/opt/conda/lib/python3.9/site-packages/CheckM2-1.0.0-py3.9.egg/checkm2/fileManager.py", line 131, in download_database
    with open(diamond_location, 'w') as dd:
PermissionError: [Errno 13] Permission denied: '/opt/conda/lib/python3.9/site-packages/CheckM2-1.0.0-py3.9.egg/checkm2/version/diamond_path.json'
```

The `diamond_path.json` file has read-all permissions (`-rw-r--r--`). 

Is checkm2 actually trying to edit a file within the package, and not just read from the file?? 

If this is the case, I highly recommend placing such editable files outside of the package itself (e.g., `${HOME}/.checkm2/`).

**Comment by michaelkarlcoleman** [comment]
Just ran into this as well.  In general, it's not proper for a program to modify files within a conda environment.  And in a multi-user environment, it definitely doesn't work.

The comment above suggests a reasonable alternative.  Or conceivably provide a flag so that the user can specify the location of the JSON file.
