### ISSUE TITLE
[Dependency Request] Generalize the dependency versions

### ISSUE THREAD

**Issue by jolespin** [chklovski/CheckM2#45]
I'm trying to establish this in my https://github.com/jolespin/veba pipeline and the prokaryotic binning module has quite a few dependencies I need to work around.

Here's the current dependency restrictions:
```
    - python >=3.6, <3.9
    - scikit-learn =0.23.2
    - h5py =2.10.0
    - numpy =1.19.2
    - diamond =2.0.4
    - tensorflow >=2.1.0, <2.6.0
    - lightgbm =3.2.1
    - pandas <=1.4.0
    - scipy
    - prodigal >=2.6.3
    - setuptools
    - requests
    - packaging
    - tqdm
 ```

#### Diamond

In particular, can Diamond allow for more versions?  Any version compatible with db version 3?

```
(checkm2_env) [jespinoz@exp-15-05 jcl110]$ diamond dbinfo -d db/checkm2/CheckM2_database/uniref100.KO.1.dmnd
diamond v2.0.4.142 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

Database format version = 3
Diamond build = 142
Sequences = 6518230
Letters = 2584051404
```

According to this thread: https://github.com/bbuchfink/diamond/issues/313#issuecomment-554949580
Any of the upcoming versions should be able to handle this database version.

##### Sklearn
Also, `sklearn` is only used for `MinMaxScaler` (https://github.com/chklovski/CheckM2/blob/d40aef910f24bf7e479e5f7ff1ed326f30d2884b/checkm2/modelProcessing.py) 

I noticed that it's not actually used here: 
https://github.com/chklovski/CheckM2/blob/d40aef910f24bf7e479e5f7ff1ed326f30d2884b/checkm2/modelProcessing.py#L19

Though, it looks like one of the models might have it in the backend: 

```
/expanse/projects/jcl110/anaconda3/envs/VEBA-binning-prokaryotic2_env/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator MinMaxScaler from version 0.23.2 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
...
Traceback (most recent call last):
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-binning-prokaryotic2_env/bin/checkm2", line 265, in <module>
    predictor.prediction_wf(False, 'auto', False, False, False)
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-binning-prokaryotic2_env/lib/python3.8/site-packages/checkm2/predictQuality.py", line 214, in prediction_wf
    specific_result_comp, scaled_features = modelProc.run_prediction_specific(vector_array, specific_model_vector_len)
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-binning-prokaryotic2_env/lib/python3.8/site-packages/checkm2/modelProcessing.py", line 68, in run_prediction_specific
    scaled_vector = self.minmax_scaler.transform(vector_array)
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-binning-prokaryotic2_env/lib/python3.8/site-packages/sklearn/preprocessing/_data.py", line 506, in transform
    if self.clip:
AttributeError: 'MinMaxScaler' object has no attribute 'clip'
```

I'm trying out a conda installation where I have different dependencies.  I installed CheckM2 in this environment via pip with --no-deps to test it out.  Just confirmed that it works with higher versions of some of the packages:

```
(base) [jespinoz@exp-15-05 checkm2]$ conda activate VEBA-binning-prokaryotic2_env
(VEBA-binning-prokaryotic2_env) [jespinoz@exp-15-05 checkm2]$ checkm2 testrun --threads 16
[01/24/2023 02:26:53 PM] INFO: Test run: Running quality prediction workflow on test genomes with 16 threads.
[01/24/2023 02:26:53 PM] INFO: Running checksum on test genomes.
[01/24/2023 02:26:53 PM] INFO: Checksum successful.
[01/24/2023 02:26:54 PM] INFO: Calling genes in 3 bins with 16 threads:
    Finished processing 3 of 3 (100.00%) bins.
[01/24/2023 02:27:12 PM] INFO: Calculating metadata for 3 bins with 16 threads:
    Finished processing 3 of 3 (100.00%) bin metadata.
[01/24/2023 02:27:12 PM] INFO: Annotating input genomes with DIAMOND using 16 threads
[01/24/2023 02:28:49 PM] INFO: Processing DIAMOND output
[01/24/2023 02:28:49 PM] INFO: Predicting completeness and contamination using ML models.
[01/24/2023 02:28:56 PM] INFO: Parsing all results and constructing final output table.
[01/24/2023 02:28:56 PM] INFO: CheckM2 finished successfully.
[01/24/2023 02:28:56 PM] INFO: Test run successful! See README for details. Results:
 Name  Completeness  Contamination         Completeness_Model_Used  Translation_Table_Used
TEST1        100.00           0.74 Neural Network (Specific Model)                      11
TEST2         98.39           0.19 Neural Network (Specific Model)                      11
TEST3         98.67           0.48 Neural Network (Specific Model)                      11
(VEBA-binning-prokaryotic2_env) [jespinoz@exp-15-05 checkm2]$ ls
CheckM2_database  checkm2_database.tar.gz  download.sh  uniref100.KO.1.dmnd
(VEBA-binning-prokaryotic2_env) [jespinoz@exp-15-05 checkm2]$ conda env export | grep -E "scikit-learn|h5py|numpy|diamond|tensorflow|lightgbm|pandas|scipy"
  - diamond=2.0.8=h56fc30b_0
  - h5py=2.10.0=nompi_py38h9915d05_106
  - lightgbm=3.3.5=py38h8dc9893_0
  - numpy=1.19.5=py38h8246c76_3
  - pandas=1.4.1=py38h43a58ef_0
  - scikit-learn=0.23.2=py38h5d63f67_3
  - scipy=1.8.0=py38h56a6a73_1
  - tensorflow=2.4.0=py38h578d9bd_0
  - tensorflow-base=2.4.0=py38h01d9eeb_0
  - tensorflow-estimator=2.4.0=pyh9656e83_0
 ```

Hope this helps!  Very much looking forward to cleaning up my `VEBA` prokaryotic binning with your tool. I had quite a few verbose workarounds to handle CPR.

**Comment by chklovski** [comment]
Hi, sorry for the later reply. MinMaxScaler is used for feature vector transformation: 

`` def run_prediction_specific(self, vector_array, specific_model_vector_len):``
        ``            scaled_vector = self.minmax_scaler.transform(vector_array)``
        
 Currently this requires a specific sklearn version, although I'm looking into alternatives. In general I've constrained the versions of several dependencies because of annoying conflicts you run into with more recent versions of numpy/scipy and especially tensorflow. Is it possible for you to have a separate (conda) environment where checkm2 dependencies are isolated from anything else? That would probably make things easier.

**Comment by chklovski** [comment]
Closed due to inactivity. Feel free to re-open if needed.
