### ISSUE TITLE
database downloading fails

### ISSUE THREAD

**Issue by ye00ye** [chklovski/CheckM2#50]
asking for help, I met problem when trying to download database 

[02/26/2023 11:59:04 PM] INFO: Command: Download database. Checking internal path information.
Traceback (most recent call last):
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f1ab1046e50>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /record/5571251 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ab1046e50>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/yanjiuyuan/Project/huangqiang/checkm2/bin/../checkm2/zenodo_backpack.py", line 164, in _retrieve_record_ID
    r = requests.get(DOI, timeout=15.)
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/yanjiuyuan/userLogin/huangqiang/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /record/5571251 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ab1046e50>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/checkm2", line 280, in <module>
    fileManager.DiamondDB().download_database(args.path)
  File "/yanjiuyuan/Project/huangqiang/checkm2/bin/../checkm2/fileManager.py", line 127, in download_database
    backpack_downloader.download_and_extract(download_location, DOI, progress_bar=True, no_check_version=False)
  File "/yanjiuyuan/Project/huangqiang/checkm2/bin/../checkm2/zenodo_backpack.py", line 46, in download_and_extract
    recordID = self._retrieve_record_ID(DOI)
  File "/yanjiuyuan/Project/huangqiang/checkm2/bin/../checkm2/zenodo_backpack.py", line 166, in _retrieve_record_ID
    raise ZenodoConnectionException('Connection error: {}'.format(e))
checkm2.zenodo_backpack.ZenodoConnectionException: Connection error: HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /record/5571251 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1ab1046e50>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by chklovski** [comment]
Hi, 

It looks like you are failing to establish a connection to Zenodo (where the database is hosted) for some reason. You can try manually downloading the current database at: `https://zenodo.org/record/5571251/files/checkm2_database.tar.gz` and then point checkm2 to is using `checkm2 database --setdblocation /path/to/downloaded_database.dmnd`

**Comment by ye00ye** [comment]
thanks for your help, i will try


| |
ye--ye
|
|
***@***.***
|
---- Replied Message ----
| From | Alex ***@***.***> |
| Date | 2/27/2023 22:22 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [chklovski/CheckM2] database downloading fails (Issue #50) |

Hi,

It looks like you are failing to establish a connection to Zenodo (where the database is hosted) for some reason. You can try manually downloading the current database at: https://zenodo.org/record/5571251/files/checkm2_database.tar.gz and then point checkm2 to is using checkm2 database --setdblocation /path/to/downloaded_database.dmnd

**Comment by chklovski** [comment]
Closed due to inactivity. Feel free to reopen if problem persists.
