### ISSUE TITLE
OSError: [Errno 95] Operation not supported

### ISSUE THREAD

**Issue by QuangOngCM** [chklovski/CheckM2#53]
Hi CheckM2 team,

I ran the checkm2 predict and it shows the error below:

```
[03/09/2023 07:24:51 AM] INFO: Running CheckM2 version 1.0.1
[03/09/2023 07:24:51 AM] INFO: Custom database path provided for predict run. Checking database at CheckM2_database/uniref100.KO.1.dmnd...
[03/09/2023 07:26:00 AM] INFO: Running quality prediction workflow with 8 threads.
[03/09/2023 07:26:01 AM] INFO: Calling genes in 7 bins with 8 threads:
Process SyncManager-1:
Traceback (most recent call last):
  File "/opt/conda/envs/checkm2_env/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/envs/checkm2_env/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/checkm2_env/lib/python3.8/multiprocessing/managers.py", line 608, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/opt/conda/envs/checkm2_env/lib/python3.8/multiprocessing/managers.py", line 154, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/opt/conda/envs/checkm2_env/lib/python3.8/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/opt/conda/envs/checkm2_env/lib/python3.8/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: [Errno 95] Operation not supported
Traceback (most recent call last):
  File "/opt/conda/envs/checkm2_env/bin/checkm2", line 210, in <module>
    predictor.prediction_wf(args.genes, mode, args.dbg_cos, args.dbg_vectors, args.stdout,
  File "/opt/conda/envs/checkm2_env/lib/python3.8/site-packages/checkm2/predictQuality.py", line 103, in prediction_wf
    GC = self.__run_prodigal(ttable)
  File "/opt/conda/envs/checkm2_env/lib/python3.8/site-packages/checkm2/predictQuality.py", line 380, in __run_prodigal
    used_ttables = mp.Manager().dict()
  File "/opt/conda/envs/checkm2_env/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/opt/conda/envs/checkm2_env/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/opt/conda/envs/checkm2_env/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/conda/envs/checkm2_env/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/opt/conda/envs/checkm2_env/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```
Do you have any idea how to troubleshoot that?

Best regards,

Quang

**Comment by chklovski** [comment]
Hi, it could be the case that you don't have writing permission to either your output directory or your /tmp? Does setting an alternate temporary directory using either `export TMPDIR=`or the `--tmpdir` command help?

**Comment by QuangOngCM** [comment]
Thank you. That is probably the reason. It is fixed now.
