### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'CheckM2==1.0.1' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by Avamost1** [chklovski/CheckM2#59]
I'm getting this error when running checkm2, what do I need to do to fix this:
Traceback (most recent call last):
  File "/home/zwc/miniconda3/envs/checkm2/bin/checkm2", line 4, in <module>
    __import__('pkg_resources').run_script('CheckM2==1.0.1', 'checkm2')
  File "/home/zwc/miniconda3/envs/amber/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3323, in <module>
    @_call_aside
  File "/home/zwc/miniconda3/envs/amber/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3298, in _call_aside
    f(*args, **kwargs)
  File "/home/zwc/miniconda3/envs/amber/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3336, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/zwc/miniconda3/envs/amber/lib/python3.7/site-packages/pkg_resources/__init__.py", line 629, in _build_master
    ws.require(__requires__)
  File "/home/zwc/miniconda3/envs/amber/lib/python3.7/site-packages/pkg_resources/__init__.py", line 966, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/zwc/miniconda3/envs/amber/lib/python3.7/site-packages/pkg_resources/__init__.py", line 828, in resolve
    req, best, replace_conflicting, env, installer, required_by, to_activate
  File "/home/zwc/miniconda3/envs/amber/lib/python3.7/site-packages/pkg_resources/__init__.py", line 868, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'CheckM2==1.0.1' distribution was not found and is required by the application

**Comment by chklovski** [comment]
Hi, sorry for the late reply. Is that using a conda installation?

**Comment by chklovski** [comment]
Closed due to inactivity, feel free to reopen if issue persists.
