### ISSUE TITLE
OSError: [Errno 30] Read-only file system

### ISSUE THREAD

**Issue by cmkobel** [chklovski/CheckM2#73]
Hi

I wish to run `checkm2 database` from apptainer in a large reproducible pipeline. checkm2 is installed with conda inside the container.

When i call the download command:
```bash
export CHECKM2DB="{params.download_path}"
checkm2 database \
                --download \
                --path {params.download_path}
```

I get the following error, because the conda prefix is in a read-only file system.
```
[08/20/2023 11:03:45 PM] INFO: Verification success.
Traceback (most recent call last):                                                                                              
  File "/conda-envs/679a46a27a9c8f5ec775838a5d75a05d/bin/checkm2", line 280, in <module>
    fileManager.DiamondDB().download_database(args.path)                                                                        
  File "/conda-envs/679a46a27a9c8f5ec775838a5d75a05d/lib/python3.8/site-packages/checkm2/fileManager.py", line 131, in download_database                                                                                                                        
    with open(diamond_location, 'w') as dd:
OSError: [Errno 30] Read-only file system: '/conda-envs/679a46a27a9c8f5ec775838a5d75a05d/lib/python3.8/site-packages/checkm2/version/diamond_path.json'
```

The thing is, I already set the CHECKM2DB system variable, so I don't need checkm2 to write to the "diamond_path.json" file.

Is there a way to disable writing to the diamond_path.json file altogether and solely rely on the CHECKM2DB system variable? I tried removing the "--path" argument, but it doesn't affect the behaviour.

Cheers,
Carl 🤟

**Comment by cmkobel** [comment]
After checking out the culprit line https://github.com/chklovski/CheckM2/blob/319dae65f1c7f2fc1c0bb160d90ac3ba64ed9457/checkm2/fileManager.py#L131 I realize that I can just ignore this "OSError". The problem is that my pipeline relies on successful exit codes to make sure that everything runs smoothly. I could maybe formulate a pull request with an added --skip-writing-to-diamond-path-dot-json like argument. 

Do you have a better solution in mind?

**Comment by cmkobel** [comment]
I recognize that my use case might be on the edge, and that it might not be worthwhile for you to spend time supporting idiosyncratic uses of CheckM2 like what I describe. Do you think it would be a better direction for me to take, to simply download the "uniref100.KO.1.dmnd" file manually from some server directly with http, and feed it into `checkm2 predict` without ever running `checkm2 database`?

**Comment by chklovski** [comment]
Hi, if you wish to download the database but not set it within CheckM2, would downloading it externally to the program and using it to set the CHECKM2DB variable an easier solution? Current database is available from the following link (I will keep this updated in the README): 

https://zenodo.org/record/5571251/files/checkm2_database.tar.gz?download=1
