### ISSUE TITLE
OSError: [Errno 16] Device or resource busy: '.nfs00000000000a4c9d00005011'

### ISSUE THREAD

**Issue by Louis-MG** [chklovski/CheckM2#75]
Hello, I am trying to run chekm2 on some reference genomes and with either my `singularity` or the `conda` environment made from the yaml (`checkm2.yml` followed by `setp.py`) I end up with this error:
```
  __import__('pkg_resources').run_script('CheckM2==1.0.2', 'checkm2')
[09/01/2023 02:17:30 PM] INFO: Running CheckM2 version 1.0.2
[09/01/2023 02:17:30 PM] INFO: Custom database path provided for predict run. Checking database at /mnt/projects_tn01/metapangenome/tools/checkm2/CheckM2_database/uniref100.KO.1.dmnd...
[09/01/2023 02:17:33 PM] INFO: Running quality prediction workflow with 100 threads.
[09/01/2023 02:17:58 PM] INFO: Calling genes in 608 bins with 100 threads:
    Finished processing 608 of 608 (100.00%) bins.
[09/01/2023 02:20:49 PM] INFO: Calculating metadata for 608 bins with 100 threads:
    Finished processing 608 of 608 (100.00%) bin metadata.
Traceback (most recent call last):
  File "/home/guelou01/miniconda3/envs/checkm2/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/guelou01/miniconda3/envs/checkm2/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/guelou01/miniconda3/envs/checkm2/lib/python3.8/multiprocessing/managers.py", line 616, in _run_server
    server.serve_forever()
  File "/home/guelou01/miniconda3/envs/checkm2/lib/python3.8/multiprocessing/managers.py", line 182, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guelou01/miniconda3/envs/checkm2/lib/python3.8/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/guelou01/miniconda3/envs/checkm2/lib/python3.8/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/guelou01/miniconda3/envs/checkm2/lib/python3.8/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/guelou01/miniconda3/envs/checkm2/lib/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/guelou01/miniconda3/envs/checkm2/lib/python3.8/shutil.py", line 675, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/guelou01/miniconda3/envs/checkm2/lib/python3.8/shutil.py", line 673, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000000000a4c9d00005011'
[09/01/2023 02:20:54 PM] INFO: Annotating input genomes with DIAMOND using 100 threads
```
Server info:
```
Linux c136-124-935 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
```
I thought my singularity was at fault and that the error was linked to [this](https://stackoverflow.com/questions/54752710/nfs-file-cant-be-removed-resource-busy-but-pid-unknown) but it fails in the `conda` environment as well. I have to end the processes myself and I dont know if it affects the results as checkm2 proceeds with Diamond.

**Comment by wwood** [comment]
Hi,

This error is likely due to an issue in the underlying file system, not checkm2, I suspect. Have you tried running it in a freshly created directory?

**Comment by Louis-MG** [comment]
This is probably due to the NFS system indeed. The directory were always created just before the job. It seems that it doesnt affect anything but the stdout, so i'll close the issue as it is not really one. Thanks !
