### ISSUE TITLE
running checkm2 issue

### ISSUE THREAD

**Issue by chantellyu** [chklovski/CheckM2#82]
i installed CheckM2 via mambaforge but when i try to run it in the command line it gives the error message as follows:

`(checkm2) cyu@ip:~/mambaforge$ checkm2
Traceback (most recent call last):
  File "/home/mambaforge/envs/checkm2/bin/checkm2", line 27, in <module>
    from checkm2 import predictQuality
  File "/home/mambaforge/envs/checkm2/lib/python3.6/site-packages/checkm2/predictQuality.py", line 1, in <module>
    from checkm2 import modelProcessing
  File "/home/mambaforge/envs/checkm2/lib/python3.6/site-packages/checkm2/modelProcessing.py", line 17, in <module>
    from tensorflow import keras
  File "/home/mambaforge/envs/checkm2/lib/python3.6/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/home/mambaforge/envs/checkm2/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 41, in <module>
    from tensorflow.python.eager import context
  File "/home/mambaforge/envs/checkm2/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 28, in <module>
    from absl import logging
  File "/home/mambaforge/envs/checkm2/lib/python3.6/site-packages/absl/logging/__init__.py", line 97, in <module>
    from absl import flags
  File "/home/mambaforge/envs/checkm2/lib/python3.6/site-packages/absl/flags/__init__.py", line 35, in <module>
    from absl.flags import _argument_parser
  File "/home/mambaforge/envs/checkm2/lib/python3.6/site-packages/absl/flags/_argument_parser.py", line 82, in <module>
    class ArgumentParser(Generic[_T], metaclass=_ArgumentParserCache):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`

**Comment by javiercnav** [comment]
Hello there, having the same issue here. I had to reinstall checkm2 today. Previously, I had a run that went smoothly

**Comment by ac-simpson** [comment]
I'm having the same problem too - just installed checkm2 via mamba, and got this exact error.

**Comment by ilnamkang** [comment]
I'm having the same error too.

**Comment by microbial-cookie** [comment]
I have the same error, too. see below:

![image](https://github.com/chklovski/CheckM2/assets/133230591/0db5daf6-4848-47db-8f06-165889a95e42)

**Comment by sklucas** [comment]
Experiencing the same error. Ubuntu 20.04.6 LTS. Everything works fine on Mac M2 Ventura 13.5.1.

**Comment by ac-simpson** [comment]
@sklucas , awesome, thank you, I now have checkm2 running properly!

**Comment by danchurch** [comment]
Also had this issue. Constraining the python version as per @sklucas worked for me.

**Comment by jsgounot** [comment]
Thanks, this should be in the readme file.
