### ISSUE TITLE
checkm2 database --download fail

### ISSUE THREAD

**Issue by YongxinLiu** [chklovski/CheckM2#85]
In CheckM2 v1.0.1
diamond v2.0.4.142

I run "checkm2 database --download" or "checkm2 database --download"

Report the following error. Can you provide a database download links? or provide a solution.

Thank you!

[10/22/2023 04:19:20 PM] INFO: Command: Download database. Checking internal path information.
Traceback (most recent call last):
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f335c64abe0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /record/5571251 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f335c64abe0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/checkm2/zenodo_backpack.py", line 164, in _retrieve_record_ID
    r = requests.get(DOI, timeout=15.)
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/sessions.py", line 725, in send
    history = [resp for resp in gen]
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/sessions.py", line 725, in <listcomp>
    history = [resp for resp in gen]
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /record/5571251 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f335c64abe0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/meta/miniconda3/envs/checkm2/bin/checkm2", line 280, in <module>
    fileManager.DiamondDB().download_database(args.path)
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/checkm2/fileManager.py", line 127, in download_database
    backpack_downloader.download_and_extract(download_location, DOI, progress_bar=True, no_check_version=False)
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/checkm2/zenodo_backpack.py", line 46, in download_and_extract
    recordID = self._retrieve_record_ID(DOI)
  File "/data/meta/miniconda3/envs/checkm2/lib/python3.8/site-packages/checkm2/zenodo_backpack.py", line 166, in _retrieve_record_ID
    raise ZenodoConnectionException('Connection error: {}'.format(e))
checkm2.zenodo_backpack.ZenodoConnectionException: Connection error: HTTPSConnectionPool(host='zenodo.org', port=443): Max retries exceeded with url: /record/5571251 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f335c64abe0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by sconlan** [comment]
You might find a temporary solution at the bottom of this issue: https://github.com/chklovski/CheckM2/issues/83

**Comment by wwood** [comment]
Closing as duplicate
