### ISSUE TITLE
AttributeError: 'Predictor' object has no attribute '__set_up_prodigal_thread'

### ISSUE THREAD

**Issue by MrOlm** [chklovski/CheckM2#97]
Hello,

I'm trying to install checkM2 on my Mac with conda, but when I do the testrun I see the following:

```
$ checkm2 testrun
[02/27/2024 02:10:46 PM] INFO: Test run: Running quality prediction workflow on test genomes with 1 threads.
[02/27/2024 02:10:46 PM] INFO: Running checksum on test genomes.
[02/27/2024 02:10:46 PM] INFO: Checksum successful.
[02/27/2024 02:10:47 PM] INFO: Calling genes in 3 bins with 1 threads:
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "/Users/mattolm/miniconda3/envs/checkm2_drep/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/mattolm/miniconda3/envs/checkm2_drep/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/mattolm/miniconda3/envs/checkm2_drep/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/mattolm/miniconda3/envs/checkm2_drep/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
    self = reduction.pickle.load(from_parent)
AttributeError: 'Predictor' object has no attribute '__set_up_prodigal_thread'
AttributeError: 'Predictor' object has no attribute '__reportProgress'
[02/27/2024 02:11:04 PM] ERROR: Error: No protein files were generated in /var/folders/dx/80rf8pdn0j551086q04ftr340000gn/T/tmp3o7y_dk6/protein_files
```

Any ideas on how to fix?

Thanks,
Matt

**Comment by jontang0** [comment]
I ran into this issue as well. I downgraded my version of python from 3.8 to 3.7 and it fixed this issue.

**Comment by rfour92** [comment]
I have the same problem on both testrun and actual MAGs. 
When I attempted to downgrade python from 3.8 to 3.7, conda was about to remove all dependencies. I couldn't find a way around it. can you kindly advise? 

by the way, I am trying to install the tool using osx-64.

**Comment by tessbrewer** [comment]
I had this issue too with the install on my M1 Mac and the python downgrade solved it. But I also had to downgrade several other dependencies and upgrade diamond. Finally these changes to the .yaml file got everything running:

`python=3.7.1`
`numpy=1.21.5`
`diamond=2.1.6`
`pandas=1.3.1`
`scipy=1.7.3`

**Comment by enzovalentino** [comment]
Hi, I'm having the same error.
I'm working on a Mac Studio with Apple Silicon. I'm trying to install checkm2 following the guidelines, and I get the 'Predictor' AttributeError. I've tried to both add ```--platform osx-64``` but I get the same error. 

I've also tried modifying the yml file, but in this case I get: 

```
conda env create -n checkm2 -f checkm2.yml 
2 channel Terms of Service accepted
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: | 
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - unsupported request
  - unsupported request
  - package tensorflow-2.17.0-cpu_py310hd689282_3 requires tensorflow-base 2.17.0 cpu_py310h6c02c0b_3, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ diamond =2.1.6 * does not exist (perhaps a typo or a missing channel);
├─ numpy =1.21.5 * is requested and can be installed;
├─ python =3.7.1 * does not exist (perhaps a typo or a missing channel);
└─ tensorflow =2.17 * is not installable because there are no viable options
   ├─ tensorflow 2.17.0 would require
   │  └─ tensorflow-base [==2.17.0 cpu_py310h6c02c0b_3|==2.17.0 cpu_py310hce8bbbd_0|==2.17.0 cpu_py39h0c1ebbd_0|==2.17.0 cpu_py39hb5ef50e_3], which requires
   │     └─ numpy >=1.22.4,<2.0a0 *, which conflicts with any installable versions previously reported;
   ├─ tensorflow 2.17.0 would require
   │  └─ tensorflow-base [==2.17.0 cpu_py311h8346247_0|==2.17.0 cpu_py311ha270cad_3|==2.17.0 cpu_py311hc1d6278_0], which requires
   │     └─ numpy >=1.23.5,<2.0a0 *, which conflicts with any installable versions previously reported;
   ├─ tensorflow 2.17.0 would require
   │  └─ tensorflow-base [==2.17.0 cpu_py312h6148f0f_0|==2.17.0 cpu_py312had574b8_3|==2.17.0 cpu_py312hdc9440d_0], which requires
   │     └─ numpy >=1.26.4,<2.0a0 *, which conflicts with any installable versions previously reported;
   └─ tensorflow 2.17.0 would require
      └─ tensorflow-base [==2.17.0 cpu_py310h2fb6de8_0|==2.17.0 cpu_py39h2fb6de8_0], which requires
         └─ numpy >=1.22.3,<2.0a0 *, which conflicts with any installable versions previously reported.
```

any help would be appreciated. 

Thanks!!

**Comment by jason-c-kwan** [comment]
I reproduced this error with CheckM2 1.1.0 and python 3.12 on MacOS Tahoe. The fix was to rename multiprocessing target methods from double-underscore private names to single-underscore names, and update the corresponding target=self... references. The following patching script works to fix it:
```bash
python - <<'PY'
import inspect
import pathlib
import shutil
import checkm2.predictQuality as pq

path = pathlib.Path(inspect.getsourcefile(pq))
backup = path.with_suffix(path.suffix + ".bak")

text = path.read_text()

replacements = {
    "def __set_up_prodigal_thread(": "def _set_up_prodigal_thread(",
    "target=self.__set_up_prodigal_thread": "target=self._set_up_prodigal_thread",

    "def __reportProgress(": "def _reportProgress(",
    "target=self.__reportProgress": "target=self._reportProgress",

    "def __set_up_metadata_thread(": "def _set_up_metadata_thread(",
    "target=self.__set_up_metadata_thread": "target=self._set_up_metadata_thread",

    "def __report_progress_metadata(": "def _report_progress_metadata(",
    "target=self.__report_progress_metadata": "target=self._report_progress_metadata",
}

new_text = text
for old, new in replacements.items():
    new_text = new_text.replace(old, new)

if new_text == text:
    print("No changes made. File may already be patched:")
    print(path)
else:
    shutil.copy2(path, backup)
    path.write_text(new_text)
    print(f"Patched: {path}")
    print(f"Backup:  {backup}")
PY
```

Save as something like `fix_checkm.sh` and then run `bash fix_checkm.sh`. Full disclosure this was written by GPT 5.4 thinking, but I tested it and it works.
